@startuml

package "Presentation tier" {
  HTTP - [Web Application]
}

package "Logic tier" {
  IFBankingService -down- [BankingService]
  IFSessionService -down- [SessionService]
  IFCustomerService -down- [CustomerService]
  
  [Web Application] ..> IFBankingService
  [Web Application] ..> IFSessionService
  [Web Application] ..> IFCustomerService


  [BankingService] -[hidden] [SessionService]
  [BankingService] -[hidden] [CustomerService]
  ' used Services
  [Chat Service] -[hidden] [Paypal]
  [Paypal] ..> IFBankingService

  [Chat Service] -- IFChatService
  IFCustomerService .> IFChatService
}

package "Data tier" {
  CustomerRepo -down- [CustomerRepository]
  AccountRepo -down- [AccountRepository]
  AddressRepo -down- [AddressRepository]
  SessionRepo -down- [SessionRepository]

  [BankingService] .> CustomerRepo
  [SessionService] .> CustomerRepo
  
  [BankingService] .> AddressRepo
  [CustomerService] .> AddressRepo
  
  [BankingService] .> AccountRepo

  [SessionService] -..> SessionRepo
}




@enduml