@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

' Declare Classes
abstract class BaseEntity{
   - id: long
   '- getId(): long
   '+ equals(object: Object): boolean
   '+ hashCode(): int
}

class Account{
  - iban: String
}

class Address{
  - street: String
  - houseNr: int
  - zipCode: long
  - city: String
  - country: String
  '+ getResidents(): List<Customer>
  '+ addResident(customer: Customer): void
}

class Customer{
  - forename: String
  - surname: String
  - username: String
  - taxNumber: String
  - birthDate: Date
  - passwordHash: String
  - password: String
}

class Employee{
   - designation: String
   - salary: double
}

class Session{
  - uuid: UUID
  - date: Date
}

class Transfer{
  - amount: double
  - date: Date
  - description: String
}


' Declare relationship of classes
Session "0..*" -- "1" Customer
Customer "1" --* "0..*" Account
Address "1" - "1..*" Customer
Transfer "0..*" - "1" Account
Transfer "0..*" - "1" Account
Customer "0..*" -- "1" Employee

BaseEntity <|-- Account
BaseEntity <|-- Address
BaseEntity <|-- Customer
BaseEntity <|-- Session
BaseEntity <|-- Transfer

Customer <|-- Employee

BaseEntity -[hidden]> Session
Transfer -[hidden]> Address
Transfer -[hidden]-> Account

@enduml