@startuml

left to right direction
skinparam monochrome true

actor "Customer" as c
actor "Employee" as e

c <|-- e

rectangle "Banking Service" as Banking {

  usecase "Create Customer Account" as uc11
  usecase "Find Customer" as uc12
  usecase "Delete Customer" as uc13
  usecase "Get Address of Customer" as uc14
  usecase "Update Address of Customer" as uc15
  usecase "Mandate Money" as uc16
  usecase "Delete Customer Account" as uc17

  usecase "Login User" as uc21

  usecase "Use Support" as uc31

  usecase "Transfer Money" as uc41
  usecase "Get Account Transfers" as uc42
  usecase "Get Account Value" as uc43
  usecase "Register Customer" as uc44
}

' Customer Service
uc11 <-- c
uc16 <-- c

e --> uc12
e --> uc13
e --> uc14
e --> uc15
e --> uc17


' Session Service
uc21 <-- c


' Support Service
'uc31 --> chat
uc31 <-- c : Ask\nQuestion
e --> uc31 : Answer\nQuestion


' Banking Service
uc41 <-- c
uc42 <-- c
uc43 <-- c
uc44 <-- c

' Layout
uc21 -[hidden]-> uc12
uc21 -[hidden]-> uc13
uc21 -[hidden]-> uc14
uc21 -[hidden]-> uc15
uc21 -[hidden]-> uc17
uc44 -[hidden]-> uc31

@enduml