@startuml

skinparam monochrome true

[Paypal\n(Gorbatschow)] as paypal
[Chat Service\n(Bielmeier)] as chat

package "Presentation" as presentation {
  HTTP - [Web Application]
}


package "Logic" as logic {

  [SessionService] -up-() SessionServiceIF
  SessionServiceIF )-up- [Web Application]

  [CustomerService] -up-() CustomerServiceIF
  CustomerServiceIF )-up- [Web Application]
  CustomerServiceIF )-- paypal

  [BankingService] -up-() BankingServiceIF
  BankingServiceIF )-- [Web Application]
  BankingServiceIF )-- paypal

  [SupportService] -up-() SupportServiceIF
  SupportServiceIF )-up- [Web Application]
  SupportServiceIF )-- chat

  'chat -[hidden]-> [SupportService]



}

package "Persistence" as persistence {
  interface " " as IF1
  interface " " as IF2
  interface " " as IF3
  interface " " as IF4
  interface " " as IF5

  [SessionRepository] -up-() IF1
  IF1 )-up- [SessionService]

  [AccountRepository] -up-() IF2
  IF2 )-up- [BankingService]

  [TransferRepository] -up-() IF3
  IF3 )-up- [BankingService]

  [CustomerRepository] -up-() IF4
  IF4 )-up- [CustomerService]

  [AddressRepository] -up-() IF5
  IF5 )-up- [CustomerService]
}

presentation -[hidden]-> logic
presentation -[hidden]-> persistence
logic -[hidden]-> persistence

logic -[hidden]> chat
paypal -[hidden]> logic




@enduml