@startuml

package "Presentation tier" as presentation {
  HTTP - [Web Application]
}

package "Logic tier" as logic {
  IFSupportService -down- [SupportService]
  IFBankingService -down- [BankingService]
  IFSessionService -down- [SessionService]
  IFCustomerService -down- [CustomerService]
  
  [Web Application] .> IFBankingService
  [Web Application] ...> IFSessionService
  [Web Application] .> IFCustomerService
  [Web Application] .> IFSupportService

  ' used Services
  [Paypal\n(Gorbatschow)] .down.> IFBankingService
  [Paypal\n(Gorbatschow)] .down.> IFCustomerService
  [Paypal\n(Gorbatschow)] .down.> IFSessionService

  IFSupportService .up.> [Chat Service\n(Bielmeier)]

}

package "Data tier" as data {
  CustomerRepo -down- [CustomerRepository]
  AccountRepo -down- [AccountRepository]
  AddressRepo -down- [AddressRepository]
  SessionRepo -down- [SessionRepository]

  [BankingService] ...> CustomerRepo
  [SessionService] ...> CustomerRepo
  
  [BankingService] .> AddressRepo
  [CustomerService] .> AddressRepo
  
  [BankingService] .> AccountRepo
  [CustomerService] .> AccountRepo

  [SessionService] -..> SessionRepo
}

presentation -[hidden]-> logic
logic -[hidden]-> data




@enduml