@startuml
left to right direction


actor "Customer" as c
actor "Employee" as e

c <|-- e

entity "Chat" as chat


rectangle Banking {
  usecase "Use Support" as uc4

  usecase "Register Customer" as uc1
  usecase "Find Customer" as uc2
  usecase "Create Account" as uc3
  usecase "Manage Customers" as uc9
  usecase "Manage Accounts" as uc10


  usecase "Open Session" as uc5
  usecase "Get Account Value" as uc6
  usecase "Transfer Money" as uc7
  usecase "Mandate Money" as uc8



}

chat <-- uc4


c --> uc1
c --> uc2
c --> uc3
'uc1 <- e
'uc2 <- e
'uc3 <- e


c --> uc5
c --> uc6
c --> uc7
c --> uc8


'uc9 <-- e
'uc10 <-- e

e-up->uc9
e-->uc10


uc8 -[hidden]- uc9
uc9 -[hidden]- uc10

c --> uc4 : Ask\nQuestion
e --> uc4 : Answer\nQuestion

@enduml