@startuml

skinparam monochrome true

[Paypal\n(Gorbatschow)] as paypal
[Chat Service\n(Bielmeier)] as chat

interface "IFSendMessage" as IFChat
chat --() IFChat

package "Presentation" as presentation {
  HTTP - [Web Application]
}


package "Logic" as logic {

  '[SessionService] -up-() SessionServiceIF
  'SessionServiceIF )-up- [Web Application]

  [CustomerService] -up-() CustomerServiceIF
  CustomerServiceIF )-up- [Web Application]
  CustomerServiceIF )-- paypal

  [BankingService] -up-() BankingServiceIF
  BankingServiceIF )-- [Web Application]
  BankingServiceIF )-- paypal

  [EmployeeService] -up-() EmployeeServiceIF
  EmployeeServiceIF )-- [Web Application]

  [SupportService] -up-() SupportServiceIF
  SupportServiceIF )-up- [Web Application]
  IFChat )-- SupportService

  'chat -[hidden]-> [SupportService]



}

package "Persistence" as persistence {

  [AccountRepository] -up-() AccountRepositoryIF
  AccountRepositoryIF )-up- [BankingService]

  [TransferRepository] -up-() TransferRepositoryIF
  TransferRepositoryIF )-up- [BankingService]

  [CustomerRepository] -up-() CustomerRepositoryIF
  CustomerRepositoryIF )-up- [CustomerService]

  [AddressRepository] -up-() AddressRepositoryIF
  AddressRepositoryIF )-up- [CustomerService]

  [EmployeeRepository] -up-() EmployeeRepositoryIF
  EmployeeRepositoryIF )-up- [EmployeeService]
}

presentation -[hidden]-> logic
presentation -[hidden]-> persistence
logic -[hidden]-> persistence

logic -[hidden]> chat
paypal -[hidden]> logic




@enduml